[build]
args_bin = []
bin = "./tmp/main"
cmd = "make air"
# Exclude dirs and files
exclude_dir = ["tmp", "vendor", "testdata", "test"]
exclude_file = []
exclude_regex = ["_test.go"]
# Include dir and files
include_dir = ["cmd", "pkg", "internal", "templates", "assets"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
send_interrupt = true
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
